services:
  - type: web
    name: todo-api
    env: docker
    plan: free

    image:
      url: ghcr.io/aryan-dot-dev/devops-assignment:latest

    envVars:
      - key: LOG_LEVEL
        value: info

    healthCheckPath: /health