services:
  - type: web
    name: todo-api
    env: docker

    image:
      url: ghcr.io/aryan-dot-dev/devops-assignment:latest
      credentials:
        username: aryan-dot-dev
        password: ${GHCR_TOKEN}

    healthCheckPath: /health